# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
loom_version = 1.15.5
minecraft_version = 26.1
loader_version = 0.18.4

# Mod Properties
mod_version = 3.0.1
mod_minecraft_version = 26.1
maven_group = me.pepperbell
archives_base_name = continuity

# Dependencies
fabric_version = 0.144.0+26.1
modmenu_version = 18.0.0-alpha.8
sodium_version = 0.8.7+mc26.1
